application: personalstock-appengine
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /www
  static_dir: www

- url: .*
  script: myproject.wsgi.application

libraries:
- name: django
  version: 1.5
